package engine

import (
	"context"
	"errors"
	"fmt"
	"io/ioutil"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/gofrs/uuid"
	"github.com/golang/protobuf/ptypes"
	grpcauth "github.com/grpc-ecosystem/go-grpc-middleware/auth"
	grpcruntime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/blep-ai/gocryptotrader_types/common"
	"github.com/blep-ai/gocryptotrader_types/common/crypto"
	"github.com/blep-ai/gocryptotrader_types/common/file"
	"github.com/blep-ai/gocryptotrader_types/common/file/archive"
	"github.com/blep-ai/gocryptotrader_types/currency"
	"github.com/blep-ai/gocryptotrader_types/database"
	"github.com/blep-ai/gocryptotrader_types/database/models/postgres"
	"github.com/blep-ai/gocryptotrader_types/database/models/sqlite3"
	"github.com/blep-ai/gocryptotrader_types/database/repository/audit"
	"github.com/blep-ai/gocryptotrader_types/exchanges/account"
	"github.com/blep-ai/gocryptotrader_types/exchanges/asset"
	"github.com/blep-ai/gocryptotrader_types/exchanges/order"
	"github.com/blep-ai/gocryptotrader_types/exchanges/orderbook"
	"github.com/blep-ai/gocryptotrader_types/exchanges/ticker"
	"github.com/blep-ai/gocryptotrader_types/gctrpc"
	"github.com/blep-ai/gocryptotrader_types/gctrpc/auth"
	gctscript "github.com/blep-ai/gocryptotrader_types/gctscript/vm"
	"github.com/blep-ai/gocryptotrader_types/log"
	"github.com/blep-ai/gocryptotrader_types/portfolio"
	"github.com/blep-ai/gocryptotrader_types/portfolio/banking"
	"github.com/blep-ai/gocryptotrader_types/portfolio/withdraw"
	"github.com/blep-ai/gocryptotrader_types/utils"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/metadata"
)
type RPCServer struct{}
